# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BDOO_GML_Loader
                                 A QGIS plugin
 Importuje BDOO w formacie GML
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import re
import shutil
import zipfile
from pathlib import Path, PurePosixPath

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QApplication,
    QFileDialog,
    QMenu,
    QMessageBox,
    QProgressBar,
)
from qgis.core import (
    Qgis,
    QgsApplication,
    QgsMessageLog,
    QgsProject,
    QgsVectorLayer,
)

from . import resources
from .constants import WOJEWODZTWA
from .geoportal import GeoportalDownloadDialog, download_geoportal_zip
from .help_tools import download_bdoo_regulation, show_about_dialog
from .layer_specs import LAYER_SPECS


# Obsługujemy historycznie spotykane rozszerzenia GML/XML oraz SHP.
# Typowa przestrzeń nazw ma postać PL.PZGiK.201.14. Wyrażenie dopuszcza też
# dodatkowy człon (np. BDOO) przed identyfikatorem terytorialnym, aby nie
# blokować paczek o nieco innej konwencji nazewniczej.
_DATA_FILE_RE = re.compile(
    r"^(PL\.PZGiK\.201(?:\.[A-Za-z0-9_-]+)*)__OT_.+\.(gml|xml|shp)$",
    re.IGNORECASE,
)

_SETTINGS_GROUP = "BDOO_GML_Loader"


class BDOO_GML_Loader:
    """Główna klasa wtyczki BDOO_GML_Loader."""

    def __init__(self, iface):
        """Zapisz interfejs QGIS i przygotuj tłumaczenia wtyczki."""
        self.iface = iface
        self.plugin_dir = Path(__file__).resolve().parent

        locale = str(QSettings().value("locale/userLocale", "en"))[:2]
        locale_path = self.plugin_dir / "i18n" / f"BDOO_GML_Loader_{locale}.qm"
        if locale_path.is_file():
            self.translator = QTranslator()
            self.translator.load(str(locale_path))
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr("&BDOO_GML")
        self.first_start = None
        self._available_source_uris = None

    @staticmethod
    def tr(message):
        """Zwróć przetłumaczony tekst interfejsu."""
        return QCoreApplication.translate("BDOO_GML_Loader", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Dodaj akcję wtyczki do menu i opcjonalnie do paska narzędzi."""
        action = QAction(QIcon(icon_path), text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
            action.setToolTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Utwórz pozycję menu i ikonę wtyczki."""
        self.add_action(
            str(self.plugin_dir / "icon.png"),
            text=self.tr("Wczytaj dane BDOO"),
            callback=self.run,
            status_tip=self.tr(
                "Wczytaj dane BDOO z katalogu, pliku ZIP albo pobierz je z Geoportalu."
            ),
            whats_this=self.tr(
                "Pozwala wskazać lokalne dane BDOO lub pobrać wojewódzką paczkę "
                "danych z Geoportalu GUGiK."
            ),
            parent=self.iface.mainWindow(),
        )
        self.first_start = True

    def unload(self):
        """Usuń elementy interfejsu dodane przez wtyczkę."""
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Wybierz źródło BDOO, zweryfikuj je i wczytaj warstwy."""
        if self.first_start:
            self.first_start = False

        source = self._select_source()
        if source is None:
            return

        dataset = self._prepare_source(*source)
        if dataset is None:
            return

        self._load_dataset(**dataset)

    def _close_plugin_windows(self):
        """Zamknij wszystkie aktualnie otwarte okna należące do wtyczki."""
        for widget in QApplication.topLevelWidgets():
            if widget.property("BDOO_GML_Loader_window"):
                widget.close()

    def _select_source(self):
        """Pozwól wybrać lokalne dane BDOO albo pobrać je z Geoportalu."""
        settings = QSettings()
        start_path = str(settings.value(f"{_SETTINGS_GROUP}/lastSource", ""))

        choice = QMessageBox(self.iface.mainWindow())
        choice.setProperty("BDOO_GML_Loader_window", True)
        choice.setWindowTitle("Źródło danych BDOO")
        choice.setIcon(QMessageBox.Question)
        choice.setText("Wybierz sposób wczytania danych BDOO.")

        folder_button = choice.addButton("katalog", QMessageBox.AcceptRole)
        folder_button.setToolTip(
            "Wskaż katalog zawierający dane BDOO w formacie GML/XML albo SHP."
        )
        zip_button = choice.addButton("plik ZIP", QMessageBox.AcceptRole)
        zip_button.setToolTip(
            "Wskaż plik ZIP zawierający dane BDOO. Archiwum nie będzie rozpakowywane."
        )
        geoportal_button = choice.addButton("Geoportal", QMessageBox.ActionRole)
        geoportal_button.setToolTip(
            "Wybierz województwo, pobierz jego paczkę BDOO z Geoportalu GUGiK "
            "i automatycznie wczytaj ją do QGIS."
        )

        # HelpRole nie zamyka okna źródła danych. Użytkownik może otworzyć
        # rozporządzenie lub informacje, a następnie wrócić do wyboru danych.
        help_button = choice.addButton("Pomoc", QMessageBox.HelpRole)
        help_button.setToolTip(
            "Otwórz menu pomocy z rozporządzeniem BDOO i informacjami o wtyczce."
        )
        help_menu = QMenu(help_button)
        help_menu.setToolTipsVisible(True)

        regulation_action = help_menu.addAction("Rozporządzenie BDOO (PDF)")
        regulation_action.setToolTip(
            "Pobierz oficjalny tekst rozporządzenia dotyczącego BDOO z systemu ELI."
        )
        regulation_action.triggered.connect(lambda: download_bdoo_regulation(choice))

        help_menu.addSeparator()
        info_action = help_menu.addAction("Informacje")
        info_action.setToolTip(
            "Wyświetl informacje o wtyczce, jej wersji, właścicielu i repozytorium."
        )
        info_action.triggered.connect(
            lambda: show_about_dialog(
                choice,
                self.plugin_dir,
                self._close_plugin_windows,
            )
        )
        help_button.setMenu(help_menu)

        cancel_button = choice.addButton("Anuluj", QMessageBox.RejectRole)
        cancel_button.setToolTip("Zamknij okno bez wczytywania danych.")

        choice.exec_()
        clicked = choice.clickedButton()

        if clicked is folder_button:
            folder = QFileDialog.getExistingDirectory(
                self.iface.mainWindow(),
                "Wybierz katalog BDOO",
                start_path,
            )
            if not folder:
                return None

            folder_path = Path(folder)
            settings.setValue(f"{_SETTINGS_GROUP}/lastSource", str(folder_path.parent))
            return "folder", folder_path

        if clicked is zip_button:
            zip_name, _ = QFileDialog.getOpenFileName(
                self.iface.mainWindow(),
                "Wybierz plik ZIP z danymi BDOO",
                start_path,
                "Archiwa ZIP (*.zip)",
            )
            if not zip_name:
                return None

            zip_path = Path(zip_name)
            settings.setValue(f"{_SETTINGS_GROUP}/lastSource", str(zip_path.parent))
            return "zip", zip_path

        if clicked is geoportal_button:
            dialog = GeoportalDownloadDialog(self.iface.mainWindow())
            dialog.setProperty("BDOO_GML_Loader_window", True)
            if dialog.exec_() != dialog.Accepted:
                return None

            zip_path = download_geoportal_zip(
                self.iface.mainWindow(),
                dialog.selected_teryt(),
                dialog.destination_directory(),
            )
            if zip_path is None:
                return None

            settings.setValue(f"{_SETTINGS_GROUP}/lastSource", str(zip_path.parent))
            return "zip", zip_path

        return None

    def _prepare_source(self, source_type, source_path):
        """Rozpoznaj przestrzeń nazw i format danych dla katalogu albo ZIP."""
        try:
            if source_type == "folder":
                records = self._scan_folder(source_path)
            else:
                records = self._scan_zip(source_path)
        except (OSError, zipfile.BadZipFile) as exc:
            QMessageBox.critical(
                self.iface.mainWindow(),
                "BDOO",
                f"Nie można odczytać wskazanego źródła:\n{exc}",
            )
            return None

        if not records:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "BDOO",
                "Nie znaleziono plików BDOO w formacie GML/XML ani SHP.",
            )
            return None

        locations = sorted({(record["parent"], record["namespace"]) for record in records})
        if len(locations) != 1:
            names = "\n".join(
                f"• {namespace}" + (f" ({parent})" if parent else "")
                for parent, namespace in locations[:10]
            )
            QMessageBox.warning(
                self.iface.mainWindow(),
                "BDOO",
                "Wskazane źródło zawiera więcej niż jeden zbiór BDOO. "
                "Wskaż katalog lub ZIP zawierający jeden zbiór.\n\n" + names,
            )
            return None

        parent, namespace = locations[0]
        selected_records = [
            record
            for record in records
            if record["parent"] == parent and record["namespace"] == namespace
        ]
        formats = sorted({record["format"] for record in selected_records})
        data_format = self._choose_format(formats)
        if data_format is None:
            return None

        selected_records = [
            record for record in selected_records if record["format"] == data_format
        ]

        if source_type == "folder":
            data_directory = source_path.resolve()
            if parent:
                data_directory = data_directory / Path(parent)
            prefix = data_directory.as_posix().rstrip("/") + "/"
            self._available_source_uris = None
        else:
            # GDAL/QGIS czyta GML/XML i SHP bezpośrednio z ZIP przez /vsizip/.
            # Dzięki temu nie tworzymy katalogów tymczasowych i nie pozostawiamy
            # rozpakowanych danych na dysku użytkownika.
            zip_prefix = f"/vsizip/{source_path.resolve().as_posix()}"
            if parent:
                zip_prefix += "/" + parent.strip("/")
            prefix = zip_prefix.rstrip("/") + "/"
            self._available_source_uris = {
                prefix + PurePosixPath(record["member"]).name
                for record in selected_records
            }

        return {
            "path": prefix,
            "przestrzen_nazw": namespace,
            "formatPliku": data_format,
        }

    @staticmethod
    def _scan_folder(folder_path):
        """Zwróć rozpoznane pliki BDOO z katalogu lub pojedynczego podkatalogu."""
        records = []
        folder_path = folder_path.resolve()

        for item in folder_path.rglob("*"):
            if not item.is_file():
                continue

            match = _DATA_FILE_RE.match(item.name)
            if not match:
                continue

            relative_parent = item.parent.relative_to(folder_path).as_posix()
            parent = "" if relative_parent == "." else relative_parent
            records.append(
                {
                    "parent": parent,
                    "namespace": match.group(1),
                    "format": match.group(2).lower(),
                    "member": item.name,
                }
            )

        return records

    @staticmethod
    def _scan_zip(zip_path):
        """Zwróć rozpoznane pliki BDOO z ZIP, także z katalogu nadrzędnego."""
        records = []
        with zipfile.ZipFile(zip_path, "r") as archive:
            for member in archive.namelist():
                if member.endswith("/"):
                    continue

                pure = PurePosixPath(member)
                match = _DATA_FILE_RE.match(pure.name)
                if not match:
                    continue

                parent = "" if str(pure.parent) == "." else pure.parent.as_posix()
                records.append(
                    {
                        "parent": parent,
                        "namespace": match.group(1),
                        "format": match.group(2).lower(),
                        "member": member,
                    }
                )

        return records

    def _choose_format(self, formats):
        """W razie obecności SHP i GML/XML pozwól użytkownikowi wybrać format."""
        formats = set(formats)
        text_formats = [fmt for fmt in ("gml", "xml") if fmt in formats]
        has_shp = "shp" in formats

        if text_formats and not has_shp:
            # Preferujemy GML, jeżeli źródło zawiera równolegle GML i XML.
            return text_formats[0]
        if has_shp and not text_formats:
            return "shp"
        if not text_formats and not has_shp:
            return None

        dialog = QMessageBox(self.iface.mainWindow())
        dialog.setWindowTitle("Format danych BDOO")
        dialog.setIcon(QMessageBox.Question)
        dialog.setText(
            "Znaleziono jednocześnie dane GML/XML i SHP. Wybierz format do wczytania."
        )
        gml_button = dialog.addButton("Wczytaj dane GML / XML", QMessageBox.AcceptRole)
        gml_button.setToolTip(
            "Wczytaj dane GML/XML i zastosuj style kartograficzne wtyczki."
        )
        shp_button = dialog.addButton("Wczytaj dane SHP", QMessageBox.AcceptRole)
        shp_button.setToolTip(
            "Wczytaj dane SHP i zastosuj style kartograficzne wtyczki."
        )
        cancel_button = dialog.addButton("Anuluj", QMessageBox.RejectRole)
        cancel_button.setToolTip("Zamknij okno bez wczytywania danych.")
        dialog.exec_()

        clicked = dialog.clickedButton()
        if clicked is gml_button:
            return text_formats[0]
        if clicked is shp_button:
            return "shp"
        return None

    def _source_exists(self, uri):
        """Sprawdź istnienie pliku zarówno na dysku, jak i wewnątrz ZIP."""
        if self._available_source_uris is not None:
            return uri in self._available_source_uris
        return Path(uri).is_file()

    def _install_svg_symbols(self):
        """Skopiuj symbole KARTO250k do katalogu SVG profilu QGIS."""
        source = self.plugin_dir / "BDOO_SVG" / "KARTO250k"
        destination = Path(QgsApplication.qgisSettingsDirPath()) / "SVG" / "KARTO250k"

        if not source.is_dir():
            QgsMessageLog.logMessage(
                f"Nie znaleziono katalogu symboli: {source}",
                "BDOO_GML_Loader",
                Qgis.Warning,
            )
            return

        try:
            shutil.copytree(source, destination, dirs_exist_ok=True)
        except OSError as exc:
            QgsMessageLog.logMessage(
                f"Nie udało się skopiować symboli KARTO250k: {exc}",
                "BDOO_GML_Loader",
                Qgis.Warning,
            )

    @staticmethod
    def _set_progress(progress, value):
        """Ustaw postęp i pozwól Qt odświeżyć interfejs podczas importu."""
        progress.setValue(value)
        QCoreApplication.processEvents()

    def _add_configured_layer(
        self,
        spec,
        path,
        przestrzen_nazw,
        formatPliku,
        target_group,
        root,
        qml_path,
    ):
        """Wczytaj pojedynczą warstwę opisaną w ``LAYER_SPECS``."""
        source_uri = f"{path}{przestrzen_nazw}__{spec['source']}.{formatPliku}"
        if not self._source_exists(source_uri):
            return None

        style_path = qml_path / spec["style"]
        if not style_path.is_file():
            QgsMessageLog.logMessage(
                f"Pominięto warstwę {spec['name']}: brak stylu {style_path.name}.",
                "BDOO_GML_Loader",
                Qgis.Warning,
            )
            return None

        layer = QgsVectorLayer(
            source_uri,
            f"{przestrzen_nazw}__{spec['name']}",
            "ogr",
        )
        if not layer.isValid():
            QgsMessageLog.logMessage(
                f"Nie udało się utworzyć warstwy z: {source_uri}",
                "BDOO_GML_Loader",
                Qgis.Warning,
            )
            return None

        if layer.featureCount() <= 0:
            return None

        QgsProject.instance().addMapLayer(layer, False)
        target_group.addLayer(layer)
        layer.loadNamedStyle(str(style_path))

        layer_node = root.findLayer(layer.id())
        if layer_node is not None:
            layer_node.setExpanded(False)

        return layer

    @staticmethod
    def _region_code(namespace):
        """Zwróć dwucyfrowy kod województwa z przestrzeni nazw, jeżeli występuje."""
        match = re.search(r"(?:^|\.)(\d{2})$", namespace)
        return match.group(1) if match else ""

    def _group_name(self, namespace):
        """Zbuduj czytelną nazwę grupy warstw dla zbioru BDOO."""
        code = self._region_code(namespace)
        if code in WOJEWODZTWA:
            if code == "00":
                return "BDOO POLSKA"
            return f"BDOO WOJEWÓDZTWO {WOJEWODZTWA[code]}"
        return f"BDOO {namespace}"

    def _dataset_already_loaded(self, root, namespace, group_name):
        """Sprawdź, czy ten sam zbiór BDOO jest już obecny w projekcie."""
        for child in root.children():
            try:
                loaded_namespace = str(
                    child.customProperty(f"{_SETTINGS_GROUP}/namespace", "")
                )
            except (AttributeError, TypeError):
                loaded_namespace = ""

            try:
                child_name = child.name()
            except AttributeError:
                child_name = ""

            if loaded_namespace == namespace or child_name == group_name:
                return True

        return False

    def _confirm_duplicate(self, namespace, group_name):
        """Zapytaj, czy ponownie wczytać zbiór obecny już w projekcie."""
        dialog = QMessageBox(self.iface.mainWindow())
        dialog.setWindowTitle("Zbiór BDOO jest już wczytany")
        dialog.setIcon(QMessageBox.Warning)
        dialog.setText(
            f"Zbiór BDOO {namespace} jest już wczytany do bieżącego projektu "
            f"w grupie „{group_name}”.\n\nCzy chcesz wczytać go ponownie?"
        )
        load_again_button = dialog.addButton("Wczytaj ponownie", QMessageBox.AcceptRole)
        load_again_button.setToolTip(
            "Dodaj ten sam zbiór BDOO do projektu jako kolejną grupę."
        )
        cancel_button = dialog.addButton("Anuluj", QMessageBox.RejectRole)
        cancel_button.setToolTip(
            "Pozostaw już wczytane dane bez dodawania kolejnej kopii."
        )
        dialog.exec_()
        return dialog.clickedButton() is load_again_button

    def _load_dataset(self, path, przestrzen_nazw, formatPliku):
        """Wczytaj wszystkie skonfigurowane warstwy BDOO do projektu QGIS."""
        root = QgsProject.instance().layerTreeRoot()
        group_name = self._group_name(przestrzen_nazw)

        if self._dataset_already_loaded(root, przestrzen_nazw, group_name):
            if not self._confirm_duplicate(przestrzen_nazw, group_name):
                return

        qml_path = self.plugin_dir / "BDOO_QML"
        self._install_svg_symbols()

        progress_message = self.iface.messageBar().createMessage(
            "Postęp importowania BDOO..."
        )
        progress = QProgressBar()
        progress.setMaximum(max(spec["progress"] for spec in LAYER_SPECS))
        progress.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        progress_message.layout().addWidget(progress)
        self.iface.messageBar().pushWidget(progress_message, Qgis.Info)

        group = root.addGroup(group_name)
        group.setCustomProperty(f"{_SETTINGS_GROUP}/namespace", przestrzen_nazw)
        group.setExpanded(False)

        group_labels = group.addGroup(f"{przestrzen_nazw} napisy")
        group_labels.setExpanded(False)
        group_points = group.addGroup(f"{przestrzen_nazw} znaki punktowe")
        group_points.setExpanded(False)

        target_groups = {
            "labels": group_labels,
            "points": group_points,
            "main": group,
        }

        loaded_count = 0
        current_progress = 0
        try:
            for spec in LAYER_SPECS:
                layer = self._add_configured_layer(
                    spec,
                    path,
                    przestrzen_nazw,
                    formatPliku,
                    target_groups[spec["target"]],
                    root,
                    qml_path,
                )
                if layer is not None:
                    loaded_count += 1

                if spec["progress"] != current_progress:
                    current_progress = spec["progress"]
                    self._set_progress(progress, current_progress)
        finally:
            self.iface.messageBar().clearWidgets()

        if loaded_count == 0:
            root.removeChildNode(group)
            QMessageBox.warning(
                self.iface.mainWindow(),
                "BDOO",
                "Nie wczytano żadnej warstwy BDOO. Sprawdź zawartość wskazanego źródła.",
            )
