# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BDOO_GML_Loader
                                 A QGIS plugin
 Importuje BDOO w formacie GML
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

WOJEWODZTWA = {
    "00": "POLSKA",
    "02": "DOLNOŚLĄSKIE",
    "04": "KUJAWSKO-POMORSKIE",
    "06": "LUBELSKIE",
    "08": "LUBUSKIE",
    "10": "ŁÓDZKIE",
    "12": "MAŁOPOLSKIE",
    "14": "MAZOWIECKIE",
    "16": "OPOLSKIE",
    "18": "PODKARPACKIE",
    "20": "PODLASKIE",
    "22": "POMORSKIE",
    "24": "ŚLĄSKIE",
    "26": "ŚWIĘTOKRZYSKIE",
    "28": "WARMIŃSKO-MAZURSKIE",
    "30": "WIELKOPOLSKIE",
    "32": "ZACHODNIOPOMORSKIE",
}
