# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BDOO_GML_Loader
                                 A QGIS plugin
 Importuje BDOO w formacie GML
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from datetime import date
from pathlib import Path

from qgis.PyQt.QtCore import QEventLoop, Qt, QUrl
from qgis.PyQt.QtGui import QDesktopServices, QPixmap
from qgis.PyQt.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QFileDialog,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QMessageBox,
    QProgressDialog,
    QVBoxLayout,
)
from qgis.core import QgsFileDownloader


# Rozporządzenie Ministra Rozwoju, Pracy i Technologii z dnia 27 lipca 2021 r.
# w sprawie bazy danych obiektów topograficznych oraz bazy danych obiektów
# ogólnogeograficznych, a także standardowych opracowań kartograficznych
# (Dz.U. 2021 poz. 1412). Ten sam akt prawny reguluje BDOT10k i BDOO.
BDOO_REGULATION_PDF_URL = "https://eli.gov.pl/api/acts/DU/2021/1412/text.pdf"
BDOO_REGULATION_FILENAME = "Rozporzadzenie_BDOO_DzU_2021_poz_1412.pdf"


def download_bdoo_regulation(parent):
    """Pobierz oficjalny PDF rozporządzenia dotyczącego BDOO."""
    default_directory = Path.home() / "Downloads"
    if not default_directory.is_dir():
        default_directory = Path.home()

    target_name, _ = QFileDialog.getSaveFileName(
        parent,
        "Zapisz rozporządzenie BDOO",
        str(default_directory / BDOO_REGULATION_FILENAME),
        "Dokument PDF (*.pdf)",
    )
    if not target_name:
        return

    target_path = Path(target_name)
    if target_path.suffix.lower() != ".pdf":
        target_path = target_path.with_suffix(".pdf")

    temporary_path = target_path.with_suffix(target_path.suffix + ".part")
    try:
        if temporary_path.exists():
            temporary_path.unlink()
    except OSError as exc:
        QMessageBox.critical(
            parent,
            "BDOO",
            f"Nie można przygotować pliku do pobrania rozporządzenia:\n{exc}",
        )
        return

    progress = QProgressDialog(
        "Pobieranie rozporządzenia BDOO…",
        "Anuluj pobieranie",
        0,
        100,
        parent,
    )
    progress.setWindowTitle("Pobieranie rozporządzenia BDOO")
    progress.setMinimumDuration(0)
    progress.setAutoClose(False)
    progress.setAutoReset(False)
    progress.show()

    state = {"completed": False, "canceled": False, "errors": []}
    downloader = QgsFileDownloader(
        QUrl(BDOO_REGULATION_PDF_URL),
        str(temporary_path),
        "",
        True,
    )

    def update_progress(received, total):
        if total > 0:
            progress.setRange(0, 100)
            progress.setValue(min(100, int(received * 100 / total)))
        else:
            progress.setRange(0, 0)

    def mark_completed(_url):
        state["completed"] = True

    def mark_canceled():
        state["canceled"] = True

    def mark_error(messages):
        state["errors"].extend(str(message) for message in messages)

    loop = QEventLoop()
    downloader.downloadProgress.connect(update_progress)
    downloader.downloadCompleted.connect(mark_completed)
    downloader.downloadCanceled.connect(mark_canceled)
    downloader.downloadError.connect(mark_error)
    downloader.downloadExited.connect(loop.quit)
    progress.canceled.connect(downloader.cancelDownload)

    downloader.startDownload()
    loop.exec_()

    try:
        progress.canceled.disconnect(downloader.cancelDownload)
    except (TypeError, RuntimeError):
        pass
    progress.close()

    if state["canceled"]:
        _safe_unlink(temporary_path)
        return

    if state["errors"] or not state["completed"]:
        _safe_unlink(temporary_path)
        details = (
            "\n".join(state["errors"])
            if state["errors"]
            else "Pobieranie nie zostało zakończone poprawnie."
        )
        QMessageBox.critical(
            parent,
            "BDOO",
            "Nie udało się pobrać rozporządzenia.\n\n" + details,
        )
        return

    try:
        if not temporary_path.is_file() or temporary_path.stat().st_size < 5:
            raise OSError("Pobrany plik jest pusty.")
        with temporary_path.open("rb") as pdf_file:
            if pdf_file.read(5) != b"%PDF-":
                raise OSError("Pobrany plik nie jest dokumentem PDF.")
        temporary_path.replace(target_path)
    except OSError as exc:
        _safe_unlink(temporary_path)
        QMessageBox.critical(
            parent,
            "BDOO",
            f"Nie można zapisać pobranego rozporządzenia:\n{exc}",
        )
        return

    if not QDesktopServices.openUrl(QUrl.fromLocalFile(str(target_path))):
        QMessageBox.information(
            parent,
            "BDOO",
            f"Rozporządzenie zostało zapisane w pliku:\n{target_path}\n\n"
            "Nie udało się otworzyć pliku automatycznie.",
        )


def show_about_dialog(parent, plugin_dir, close_all_callback=None):
    """Wyświetl okno „Informacje” zgodne z rozwiązaniem z wtyczki BDOT10k."""
    plugin_dir = Path(plugin_dir)
    metadata = _read_plugin_metadata(plugin_dir / "metadata.txt")

    plugin_name = metadata.get("name", "BDOO_GML")
    version = metadata.get("version", "")
    repository = metadata.get(
        "repository",
        "https://github.com/MarcinLebiecki/BDOO_GML",
    )
    tracker = metadata.get(
        "tracker",
        repository.rstrip("/") + "/issues",
    )
    documentation = metadata.get(
        "homepage",
        repository,
    ).rstrip("/") + "#readme"

    dialog = QDialog(parent)
    dialog.setProperty("BDOO_GML_Loader_window", True)
    dialog.setWindowTitle("Informacje")
    dialog.setModal(True)
    dialog.resize(600, 450)
    dialog.setMinimumSize(560, 420)

    main_layout = QVBoxLayout(dialog)
    main_layout.setContentsMargins(0, 0, 0, 0)
    main_layout.setSpacing(0)

    info_frame = QFrame(dialog)
    info_frame.setFrameShape(QFrame.StyledPanel)
    info_frame.setFrameShadow(QFrame.Sunken)
    info_frame.setStyleSheet("QFrame { background: white; }")
    info_layout = QGridLayout(info_frame)
    info_layout.setContentsMargins(80, 36, 34, 32)
    info_layout.setHorizontalSpacing(42)
    info_layout.setVerticalSpacing(24)
    info_layout.setColumnMinimumWidth(0, 145)
    info_layout.setColumnStretch(1, 1)

    def add_value_row(row, label_text, value_text, href=None):
        label = QLabel(label_text, info_frame)
        label.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        info_layout.addWidget(label, row, 0)

        value = QLabel(info_frame)
        if href:
            value.setText(f"<a href='{href}'>{value_text}</a>")
            value.setTextFormat(Qt.RichText)
            value.setOpenExternalLinks(True)
            value.setTextInteractionFlags(Qt.TextBrowserInteraction)
        else:
            value.setText(value_text)
        value.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        info_layout.addWidget(value, row, 1)

    add_value_row(0, "Nazwa wtyczki:", plugin_name)
    add_value_row(1, "Wersja wtyczki:", version)
    add_value_row(2, "Repozytorium kodu:", "github", repository)
    add_value_row(3, "Zgłaszanie błędów:", "zgłoś błąd", tracker)
    add_value_row(
        4,
        "Dokumentacja użytkownika:",
        "Pobierz dokumentację użytkownika",
        documentation,
    )
    add_value_row(
        5,
        "Licencja:",
        "GNU GPL v3.0",
        "https://www.gnu.org/licenses/gpl-3.0.html",
    )
    add_value_row(6, "Właściciel:", "GUGiK")

    main_layout.addWidget(info_frame, 1)

    bottom_frame = QFrame(dialog)
    bottom_layout = QHBoxLayout(bottom_frame)
    bottom_layout.setContentsMargins(0, 8, 4, 6)
    bottom_layout.setSpacing(10)

    branding_layout = QVBoxLayout()
    branding_layout.setContentsMargins(16, 0, 0, 0)
    branding_layout.setSpacing(3)

    logo_label = QLabel(bottom_frame)
    logo_path = plugin_dir / "gugik_logo.png"
    if logo_path.is_file():
        logo_pixmap = QPixmap(str(logo_path))
        if not logo_pixmap.isNull():
            logo_label.setPixmap(
                logo_pixmap.scaled(
                    118,
                    68,
                    Qt.KeepAspectRatio,
                    Qt.SmoothTransformation,
                )
            )
    logo_label.setFixedSize(120, 70)
    logo_label.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
    branding_layout.addWidget(logo_label)

    current_year = date.today().year
    gugik_link = QLabel(
        f"<a href='https://www.gov.pl/web/gugik'>GUGiK {current_year}</a>",
        bottom_frame,
    )
    gugik_link.setTextFormat(Qt.RichText)
    gugik_link.setOpenExternalLinks(True)
    gugik_link.setTextInteractionFlags(Qt.TextBrowserInteraction)
    gugik_link.setFixedWidth(120)
    gugik_link.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
    branding_layout.addWidget(gugik_link)

    bottom_layout.addLayout(branding_layout)
    bottom_layout.addStretch(1)

    buttons = QDialogButtonBox(
        QDialogButtonBox.Ok | QDialogButtonBox.Cancel,
        Qt.Horizontal,
        bottom_frame,
    )
    ok_button = buttons.button(QDialogButtonBox.Ok)
    cancel_button = buttons.button(QDialogButtonBox.Cancel)
    if ok_button is not None:
        ok_button.setText("Zamknij")
        ok_button.setToolTip("Zamknij wszystkie okna wtyczki.")
    if cancel_button is not None:
        cancel_button.setText("Wróć")
        cancel_button.setToolTip("Wróć do poprzedniego okna.")
    if close_all_callback is None:
        buttons.accepted.connect(dialog.accept)
    else:
        buttons.accepted.connect(close_all_callback)
    buttons.rejected.connect(dialog.reject)
    bottom_layout.addWidget(buttons, 0, Qt.AlignBottom | Qt.AlignRight)

    main_layout.addWidget(bottom_frame)
    dialog.exec_()


def _read_plugin_metadata(metadata_path):
    """Odczytaj podstawowe pola z sekcji [general] pliku metadata.txt."""
    values = {}
    try:
        for raw_line in metadata_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith(("#", ";", "[")) or "=" not in line:
                continue
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip()
    except OSError:
        pass
    return values


def _safe_unlink(path):
    """Usuń plik pomocniczy bez zgłaszania błędu."""
    try:
        Path(path).unlink()
    except OSError:
        pass
