# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BDOO_GML_Loader
                                 A QGIS plugin
 Importuje BDOO w formacie GML
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# Kolejność jest zgodna z dotychczasową wersją wtyczki BDOO_GML_Loader.
# target: labels -> grupa napisów, points -> grupa znaków punktowych,
# main -> główna grupa województwa.
LAYER_SPECS = (
    {
        "progress": 1,
        "source": "OT_ADMS_P",
        "name": "nazwy miejscowości",
        "style": "OT_ADMS_P__nazwy_miejscowosci.qml",
        "target": "labels",
    },
    {
        "progress": 2,
        "source": "OT_SKDR_L",
        "name": "szlaki drogowe",
        "style": "OT_SKDR_L__szlaki_drogowe.qml",
        "target": "labels",
    },
    {
        "progress": 3,
        "source": "OT_SWRS_L",
        "name": "nazwy rzek",
        "style": "OT_SWRS_L__nazwy_rzek.qml",
        "target": "labels",
    },
    {
        "progress": 4,
        "source": "OT_PTWP_A",
        "name": "nazwy wód powierzchniowych",
        "style": "OT_PTWP_A__nazwy_wod_powierzchniowych.qml",
        "target": "labels",
    },
    {
        "progress": 5,
        "source": "OT_TCPN_A",
        "name": "nazwy parków narodowych",
        "style": "OT_TCPN_A__nazwy_parkow_narodowych.qml",
        "target": "labels",
    },
    {
        "progress": 6,
        "source": "OT_TCRZ_A",
        "name": "nazwy rezerwatów",
        "style": "OT_TCRZ_A__nazwy_rezerwatow.qml",
        "target": "labels",
    },
    {
        "progress": 7,
        "source": "OT_TCPK_A",
        "name": "nazwy parków krajobrazowych",
        "style": "OT_TCPK_A__nazwy_parkow_krajobrazowych.qml",
        "target": "labels",
    },
    # W wersji 2.0.1 znajdowało się odwołanie do nieistniejącego stylu
    # OT_KUKO_A__nazwy_kompleksow.qml. Nie tworzymy sztucznego stylu ani
    # nie podmieniamy go na styl innej klasy — pozostałe warstwy są ładowane
    # niezależnie i bez ryzyka przerwania importu.
    {
        "progress": 9,
        "source": "OT_ADMS_P",
        "name": "OT_ADMS_P",
        "style": "OT_ADMS_P.qml",
        "target": "points",
    },
    {
        "progress": 10,
        "source": "OT_TCRZ_A",
        "name": "OT_TCRZ_A",
        "style": "OT_TCRZ_A_pkt.qml",
        "target": "points",
    },
    {
        "progress": 11,
        "source": "OT_KUPG_P",
        "name": "OT_KUPG_P",
        "style": "OT_KUPG_P.qml",
        "target": "points",
    },
    {
        "progress": 12,
        "source": "OT_KUKO_P",
        "name": "OT_KUKO_P",
        "style": "OT_KUKO_P.qml",
        "target": "points",
    },
    {
        "progress": 13,
        "source": "OT_OIKM_P",
        "name": "OT_OIKM_P",
        "style": "OT_OIKM_P.qml",
        "target": "points",
    },
    {
        "progress": 14,
        "source": "OT_SULN_L",
        "name": "OT_SULN_L",
        "style": "OT_SULN_L.qml",
        "target": "main",
    },
    {
        "progress": 15,
        "source": "OT_SKPP_L",
        "name": "OT_SKPP_L",
        "style": "OT_SKPP_L.qml",
        "target": "main",
    },
    {
        "progress": 16,
        "source": "OT_SKTR_L",
        "name": "OT_SKTR_L",
        "style": "OT_SKTR_L.qml",
        "target": "main",
    },
    {
        "progress": 17,
        "source": "OT_SKDR_L",
        "name": "OT_SKDR_L",
        "style": "OT_SKDR_L.qml",
        "target": "main",
    },
    {
        "progress": 18,
        "source": "OT_ADJA_A",
        "name": "OT_ADJA_A",
        "style": "OT_ADJA_A.qml",
        "target": "main",
    },
    {
        "progress": 19,
        "source": "OT_TCPN_A",
        "name": "OT_TCPN_A",
        "style": "OT_TCPN_A.qml",
        "target": "main",
    },
    {
        "progress": 20,
        "source": "OT_TCPK_A",
        "name": "OT_TCPK_A",
        "style": "OT_TCPK_A.qml",
        "target": "main",
    },
    {
        "progress": 21,
        "source": "OT_KUPW_A",
        "name": "OT_KUPW_A",
        "style": "OT_KUPW_A.qml",
        "target": "main",
    },
    {
        "progress": 22,
        "source": "OT_BUUO_L",
        "name": "OT_BUUO_L",
        "style": "OT_BUUO_L.qml",
        "target": "main",
    },
    {
        "progress": 23,
        "source": "OT_PTWP_A",
        "name": "OT_PTWP_A",
        "style": "OT_PTWP_A.qml",
        "target": "main",
    },
    {
        "progress": 24,
        "source": "OT_SWKN_L",
        "name": "OT_SWKN_L",
        "style": "OT_SWKN_L.qml",
        "target": "main",
    },
    {
        "progress": 25,
        "source": "OT_SWRS_L",
        "name": "OT_SWRS_L",
        "style": "OT_SWRS_L.qml",
        "target": "main",
    },
    {
        "progress": 26,
        "source": "OT_OIMK_A",
        "name": "OT_OIMK_A",
        "style": "OT_OIMK_A.qml",
        "target": "main",
    },
    {
        "progress": 27,
        "source": "OT_KUSC_A",
        "name": "OT_KUSC_A",
        "style": "OT_KUSC_A.qml",
        "target": "main",
    },
    {
        "progress": 28,
        "source": "OT_PTZB_A",
        "name": "OT_PTZB_A",
        "style": "OT_PTZB_A.qml",
        "target": "main",
    },
    {
        "progress": 29,
        "source": "OT_PTUT_A",
        "name": "OT_PTUT_A",
        "style": "OT_PTUT_A.qml",
        "target": "main",
    },
    {
        "progress": 30,
        "source": "OT_PTGN_A",
        "name": "OT_PTGN_A",
        "style": "OT_PTGN_A.qml",
        "target": "main",
    },
    {
        "progress": 31,
        "source": "OT_PTRK_A",
        "name": "OT_PTRK_A",
        "style": "OT_PTRK_A.qml",
        "target": "main",
    },
    {
        "progress": 32,
        "source": "OT_PTNZ_A",
        "name": "OT_PTNZ_A",
        "style": "OT_PTNZ_A.qml",
        "target": "main",
    },
    {
        "progress": 33,
        "source": "OT_PTLZ_A",
        "name": "OT_PTLZ_A",
        "style": "OT_PTLZ_A.qml",
        "target": "main",
    },
    {
        "progress": 34,
        "source": "OT_PTTR_A",
        "name": "OT_PTTR_A",
        "style": "OT_PTTR_A.qml",
        "target": "main",
    },
)
